# Generated by Django 4.0.2 on 2022-02-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junior_hunter', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(
                    sql='ALTER TABLE junior_hunter_specialty DROP COLUMN "picture" ',
                    reverse_sql='ALTER TABLE junior_hunter_specialty ADD COLUMN "picture" varchar(200) NOT NULL',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE junior_hunter_specialty ADD COLUMN "picture" varchar(200) NOT NULL default "https://place-hold.it/100x60"',
                    reverse_sql='ALTER TABLE junior_hunter_specialty DROP COLUMN "picture" ',
                ),
            ])]