# Generated by Django 4.0.2 on 2022-03-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junior_hunter', '0004_add_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_images'),
        ),
    ]
